version: '3'

services:
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    container_name: UserDB
    environment:
      MYSQL_ROOT_PASSWORD: Kilabilon258!
      MYSQL_DATABASE: Delivery
      MYSQL_USER: API
      MYSQL_PASSWORD: Kilabilon258!
    ports:
      - "3306:3307"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: DeliveryPMA
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:81
  cubeapi:
    platform: linux/amd64
    image: valden01/delivery
    ports:
      - 8081:8081
    environment:
      DB_SERVER: mysqldb
      DB_NAME: Delivery
      DB_USERNAME: API
      DB_PASSWORD: Kilabilon258!
    depends_on:
      - mysqldb
volumes:
  dbdata: