apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: valden01/delivery:latest
          ports:
            - name: http
              containerPort: 8082
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  type: LoadBalancer
  selector:
    app: delivery
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 8082
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082